apiVersion: v1
kind: Service
metadata:
  name: real-time-code-editor-service
spec:
  selector:
    app: real-time-code-editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
